---
- hosts: rmp
  serial: 1
  roles:
  - apigee-opdk-setup-default-settings
  - { role: apigee-opdk-server-self, server_type: 'router'}
  - { role: apigee-opdk-server-self, server_type: 'mp'}

- hosts: pg
  serial: 1
  roles:
  - apigee-opdk-setup-default-settings
  - { role: apigee-opdk-server-self, server_type: 'ps'}

- hosts: qpid
  serial: 1
  roles:
  - apigee-opdk-setup-default-settings
  - { role: apigee-opdk-server-self, server_type: 'qs'}

- hosts: ms
  serial: 1
  roles:
  - apigee-opdk-setup-default-settings
  - { role: apigee-opdk-server-self, server_type: 'ms'}
