---
- hosts: '{{ hosts }}'
  strategy: free
  vars_files:
  - ~/.apigee/credentials.yml
  roles:
  - apigee-opdk-enable-swap
  - apigee-opdk-setup-default-settings
  - apigee-opdk-setup-os-postgres
  tags:
  - os-pre-req

- hosts: '{{ hosts }}'
  strategy: free
  vars_files:
  - ~/.apigee/credentials.yml
  roles:
  - apigee-opdk-setup-default-settings
  - apigee-opdk-setup-postgres-config
  tags:
  - apigee-pre-req

- include: opdk-install-component.yml
  vars:
    hosts: '{{ hosts }}'
    component_profile: 'ps'
  tags:
  - apigee-component

- include: 'opdk-setup-postgres-master.yml'
  when: pg_component is defined and pg_component == 'master'
  tags:
  - apigee-component

- include: 'opdk-setup-postgres-standby.yml'
  when: pg_component is defined and pg_component == 'standby'
  tags:
  - apigee-component

- hosts: '{{ hosts }}'
  serial: 1
  roles:
  - apigee-opdk-setup-default-settings
  tasks:
  - name: Obtain server self report
    opdk_server_self:
      server_type: 'ps'
      username: '{{ opdk_user_email }}'
      password: '{{ opdk_user_pass }}'
    ignore_errors: yes
