---
- hosts: '{{ hosts }}'
  vars_files:
  - ~/.apigee/credentials.yml
  roles:
  - apigee-opdk-setup-default-settings
  - { role: apigee-opdk-server-self, server_types: ['ps']}
  - apigee-opdk-setup-postgresql-add

