---
- hosts: '{{ hosts }}'
  serial: 1
  roles:
  - apigee-opdk-setup-default-settings
  - apigee-opdk-setup-component-installer
  - { role: apigee-opdk-setup-component, profile: '{{ component_profile }}' }
#  - { role: apigee-fetch-files, fetch_files: '{{ apigee_log_files }}', fetched_files_dir: '{{ fetched_logs_dir }}' }
  tags:
  - apigee-component
