---
- hosts: '{{ hosts }}'
  strategy: free
  vars_files:
  - ~/.apigee/credentials.yml
  roles:
  - { role: apigee-opdk-set-reachable, reachable: '{{ reachability }}', server_types: ['router', 'mp'] }
  tags:
  - reachability